title: IOOS Code Sprint
menu_title: IOOS Code Sprint
author: Integrated Ocean Observing System (IOOS) Office, 
  Great Lakes Observing System (GLOS), Mid-Atlantic Regional Association Coastal Ocean Observing System (MARACOOS)
description:
  The IOOS Code Sprint is a multi-day hackathon style event, organised by the
  Integrated Ocean Observing System (IOOS) Office and IOOS Regional Associations 
  (RA). Over the course of the event, teams of developers 
  and academic researchers from across the IOOS community will work on 
  projects related to the IOOS mission to produce, integrate, and communicate 
  high quality ocean, coastal and Great Lakes information that meets the 
  safety, economic, and stewardship needs of the Nation.
url: "https://ioos.github.io"
baseurl: "/ioos-code-sprint"
repository: "ioos/ioos-code-sprint"
#github_username: ioos-code-sprint
theme: minima
header_pages:
  - registration.md
  - agenda.md
#  - topics.md
  - videos-slides.md
#  - _resources.md
  - about.md

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
#   closed = Registration form is now closed
registration_status_2022: closed
registration_status_2024: closed

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  topics:
    output: true
    permalink: :year/:collection/:title:output_ext
  agendas:
    output: true
    permalink: :year/:title:output_ext
  homepages:
    output: true
    permalink: :year/:title:output_ext
  registrations:
    output: true
    permalink: :year/:title:output_ext
  abouts:
    output: true
    permalink: :year/:title:output_ext
  resources:
    output: true
    permalink: :year/:title:output_ext

future: true
# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/cs_graphic.png
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
